# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: false

tasks:
  install:
    desc: Install deps and tools
    deps: [install:deps, install:tools]
    cmds:
      - task: install:hooks

  install:deps:
    desc: Install dependencies
    cmds:
      - go mod download
      - task: check:tidy

  install:tools:
    desc: Install tools
    cmds:
      - go install github.com/air-verse/air@latest
      - go install github.com/evilmartians/lefthook/v2@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  install:hooks:
    desc: Install lefthook hooks
    cmds:
      - lefthook install

  check:
    desc: Check vulnerabilities and dependencies
    deps: [check:tidy, check:vuln, check:lefthook]

  check:vuln:
    desc: Check and detect vulnerabilities
    cmds:
      - govulncheck ./...

  check:tidy:
    desc: Check dependencies
    cmds:
      - go mod tidy
      - go mod verify

  check:lefthook:
    desc: Check lefthook install
    cmds:
      - lefthook validate

  copy:pkgx:
    desc: Copy pkgx packages
    cmds:
      - rsync -av --delete ../pkgx/ ./pkg/

  tidy:
    cmd: go mod tidy

  generate:
    cmd: ""

  dev:
    desc: Run in dev mode
    cmd: air

  run:
    desc: Run in simple mode
    cmd: go run ./cmd/main.go

  build:
    desc: Build package
    cmd: go build ./cmd/main.go

  test:
    desc: Test package
    cmd: go test ./...
